version: '3.9'

services:
  client:
    extends:
      file: ./apps/client/docker-compose.yaml
      service: client
    build:
      context: ./
      dockerfile: ./apps/client/Dockerfile
    networks:
      - bo_api
      - bo_client

  api:
    extends:
      file: ./apps/api/docker-compose.yaml
      service: api
    build:
      target: production
      context: ./
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - ./envs/coin_market_cap.env
      - ./envs/pg.env
      - ./envs/jwt.env
    command: npm run start:prod
    networks:
      - bo_api
      - bo_client
    depends_on:
      - postgres

  postgres:
    extends:
      file: ./docker/docker-compose-postgres.yaml
      service: postgres
    volumes:
      - bo_db:/var/lib/postgresql/data
    networks:
      - bo_api

networks:
  bo_api:
    driver: bridge
  bo_client:
    driver: bridge

volumes:
  bo_db:
