version: "3.9"

services:
  postgres:
    container_name: "postgres"
    image: postgres:16-alpine
    restart: "on-failure"
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
    postgres_db: